version: "3"
services:
  web:
    image: golang:1.15.6-alpine
    build:
      context: . 
      dockerfile: Dockerfile.local
  databases:
    image: mongo:4.4.3
    ports: "27017:27017" # The Http port
